wasm:
	wasm-pack build

test:
	RUST_BACKTRACE=1 cargo test -- --nocapture

run:
	cd www && npm run start

# misc installing stuff here
# npm install typescript --save-dev
# npm install ts-loader --save-dev
